name: dfctl-scan
on:
  workflow_dispatch:
    inputs:
      dfctlversion:
        description: 'dfctl version to use'
        required: true
        default: '3.4.0-2468'
  pull_request:
    branches: [master]
    types: [opened, reopened]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: scan filesystem with dfctl
        env: 
          DFCTL_VERSION: ${{ github.event.inputs.dfctlversion || 'latest' }}
          DF_RUN_TOKEN: ${{ secrets.DFSCAN_TOKEN }}
          APP_NAME: ${{ github.event.repository.name }}
          COMP_NAME: ${{ github.base_ref }}
          PROJDIR: ${{ github.workspace }}
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            repoVersion=${{ github.head_ref }}
          else
            repoVersion=${{ github.ref_name }}
          fi
          echo "Running command 'docker run --pull=always --rm -e DF_RUN_TOKEN=$DF_RUN_TOKEN -v $PROJDIR:/home/projdir -v /var/run/docker.sock:/var/run/docker.sock  public.ecr.aws/deepfactor/df/runtime:$DFCTL_VERSION dfctl scan -s fs -a $APP_NAME -c $APP_NAME -V $repoVersion /home/projdir'"
          docker run --pull=always --rm -e DF_RUN_TOKEN=$DF_RUN_TOKEN -v $PROJDIR:/home/projdir -v /var/run/docker.sock:/var/run/docker.sock  public.ecr.aws/deepfactor/df/runtime:$DFCTL_VERSION dfctl scan -s fs -a $APP_NAME -c $APP_NAME -V $repoVersion /home/projdir
